[tool.poetry]
name = "brownbag"
version = "0.1.0"
description = "Demos for a brown bag"
authors = ["Andrew Schwartzmeyer <andrew@schwartzmeyer.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.1.1"
fabric = "^2.5.0"
tenacity = "^6.2.0"
PyYAML = "^5.3.1"
schema = "^0.7.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-isort = "^4.0.0"
isort = "^5.6.1"
mypy = "^0.782"
pyls-black = "^0.4.6"
pyls-isort = "^0.2.0"
pyls-mypy = "^0.1.8"
pytest-flake8 = "^1.0.6"
pytest-mypy = "^0.7.0"
python-language-server = "^0.35.1"
rope = "^0.18.0"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
